//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_AoNuoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachHang
    {
        public string maKH { get; set; }
        public string hoTen { get; set; }
        public string diaChi { get; set; }
        public string masoThue { get; set; }
        public string soDT { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string moTa { get; set; }
    }
}
