//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_AoNuoi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PM_NuoiCaEntities : DbContext
    {
        public PM_NuoiCaEntities()
            : base("name=PM_NuoiCaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aoNuoi> aoNuois { get; set; }
        public virtual DbSet<dviTinh> dviTinhs { get; set; }
        public virtual DbSet<khachHang> khachHangs { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<nganhHang> nganhHangs { get; set; }
        public virtual DbSet<nhaCungCap> nhaCungCaps { get; set; }
        public virtual DbSet<nhomHang> nhomHangs { get; set; }
        public virtual DbSet<phieuNhap> phieuNhaps { get; set; }
        public virtual DbSet<phieuThuChi> phieuThuChis { get; set; }
        public virtual DbSet<phieuXuat> phieuXuats { get; set; }
        public virtual DbSet<QLKho> QLKhoes { get; set; }
        public virtual DbSet<sanPham> sanPhams { get; set; }
        public virtual DbSet<vungNuoi> vungNuois { get; set; }
    }
}
