//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_AoNuoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuNhap
    {
        public string maPN { get; set; }
        public string tenLoaiPN { get; set; }
        public string Duyet { get; set; }
        public string CanPhieuChi { get; set; }
    }
}
