//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_AoNuoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuXuat
    {
        public string maPX { get; set; }
        public string tenLoaiPX { get; set; }
        public string CanPhieuThu { get; set; }
        public string loaiGia { get; set; }
    }
}
